// === 자동 생성 파일 — tools/preprocess.mjs 가 생성함. 직접 수정 금지 ===
// 미션: 시간대=열 위치(진실), 난이도=괄호 우선·누락 시 행 위치 보정.
// 총 108개. 글귀: 시조 14 + 속담 11 = 25개.

const MISSIONS = [
  { id: "out-30-up-1", category: "아웃도어", duration: 30, difficulty: "상", text: "혼자 팝업 스토어 예약 티켓팅 하기" },
  { id: "out-60-up-1", category: "아웃도어", duration: 60, difficulty: "상", text: "러닝화만 신고 체력의 한계까지 러닝하기" },
  { id: "out-90-up-1", category: "아웃도어", duration: 90, difficulty: "상", text: "자전거 빌려서, 오르막길이 포함된 새로운 코스로 목적지 없이 페달 밟으며 땀 흘리기" },
  { id: "out-120-up-1", category: "아웃도어", duration: 120, difficulty: "상", text: "현 위치에서 가장 가까운 버스 정류장에 가서, 가장 먼저 도착하는 버스의 5번째 정류장에서 내려 동네 구경하기" },
  { id: "out-150-up-1", category: "아웃도어", duration: 150, difficulty: "상", text: "한 번도 가본 적 없는 이웃 동네의 가장 큰 전통시장에 가서, 그곳의 명물 먹거리로만 삼시세끼 중 한 끼 해결하고 오기" },
  { id: "out-180-up-1", category: "아웃도어", duration: 180, difficulty: "상", text: "편도 1시간 30분 거리의 새로운 명소 걸어서 왕복하기" },
  { id: "out-30-mid-1", category: "아웃도어", duration: 30, difficulty: "중", text: "6개월 후 여행지 교통편 예매하기" },
  { id: "out-60-mid-1", category: "아웃도어", duration: 60, difficulty: "중", text: "동네 시장이나 마트에 가서 낯선 식재료 사오기" },
  { id: "out-90-mid-1", category: "아웃도어", duration: 90, difficulty: "중", text: "동네 서점, 소품샵 가서 책 한 권 사오기" },
  { id: "out-120-mid-1", category: "아웃도어", duration: 120, difficulty: "중", text: "카메라(또는 스마트폰) 하나만 들고 나가, 오늘 날씨의 색감이 잘 드러나는 풍경 사진 10장 찍어오기" },
  { id: "out-150-mid-1", category: "아웃도어", duration: 150, difficulty: "중", text: "근처의 낮은 야산이나 등산로 코스를 찾아 입구부터 정상까지 다녀오기" },
  { id: "out-180-mid-1", category: "아웃도어", duration: 180, difficulty: "중", text: "번화가 핫플 카페 투어 및 미술관·전시 관람하기" },
  { id: "out-30-low-1", category: "아웃도어", duration: 30, difficulty: "하", text: "동네에서 가장 좋아하는 가로수길이나 공원 벤치에 앉아 아무것도 안 하고 멍하니 바람 맞기" },
  { id: "out-60-low-1", category: "아웃도어", duration: 60, difficulty: "하", text: "근처에서 가장 높은 건물 옥상에 올라가서 경치 구경하기" },
  { id: "out-90-low-1", category: "아웃도어", duration: 90, difficulty: "하", text: "지도 어플 없이 동네 산책하며 낯선 골목 발견하기" },
  { id: "out-120-low-1", category: "아웃도어", duration: 120, difficulty: "하", text: "이어폰으로 평소 안 듣던 장르의 음악 앨범을 통째로 들으며,한강변이나 큰 개천을 따라 쭉 걸어갔다 돌아오기" },
  { id: "out-150-low-1", category: "아웃도어", duration: 150, difficulty: "하", text: "대형 쇼핑몰, 아울렛에 가서 윈도우 쇼핑하며 요즘 트렌드 구경하기" },
  { id: "out-180-low-1", category: "아웃도어", duration: 180, difficulty: "하", text: "외곽 카페나 공원에서 책 완독하거나 다이어리 쓰기" },
  { id: "art-30-up-1", category: "문화예술", duration: 30, difficulty: "상", text: "평소 어렵게 느꼈던 클래식 독주곡을 헤드폰으로 숨소리까지 집중해서 완청하기" },
  { id: "art-60-up-1", category: "문화예술", duration: 60, difficulty: "상", text: "요즘 떠오르는 미디어 아트나 짧은 독립 단편 영화 한 편 찾아보기" },
  { id: "art-90-up-1", category: "문화예술", duration: 90, difficulty: "상", text: "시집이나 수필집을 소리 내어 낭독하며 마음에 드는 문장 필사하기" },
  { id: "art-120-up-1", category: "문화예술", duration: 120, difficulty: "상", text: "평소 안 가본 미술관이나 갤러리의 도슨트 투어 들으며 관람하기" },
  { id: "art-150-up-1", category: "문화예술", duration: 150, difficulty: "상", text: "전통 음악이나 예술의 역사·기원을 다룬 다큐멘터리 정주행하기" },
  { id: "art-180-up-1", category: "문화예술", duration: 180, difficulty: "상", text: "예술 영화 전용 상영관에 가서 평소 접하기 힘든 독립·실험 영화 보고 오기" },
  { id: "art-30-mid-1", category: "문화예술", duration: 30, difficulty: "중", text: "올해 크리스마스에 하고 싶은 일 리스트 작성하기. 함께하고 싶은 사람이 있다면, 그 사람에게 리스트 보내기" },
  { id: "art-60-mid-1", category: "문화예술", duration: 60, difficulty: "중", text: "산책하며 식물 사진 찍기" },
  { id: "art-90-mid-1", category: "문화예술", duration: 90, difficulty: "중", text: "좋아하는 동네 카페에서 오롯이 음악만 들으며 시각과 청각에 집중하기" },
  { id: "art-120-mid-1", category: "문화예술", duration: 120, difficulty: "중", text: "좋아하는 아티스트의 라이브 공연 실황 영상 찾아보기" },
  { id: "art-150-mid-1", category: "문화예술", duration: 150, difficulty: "중", text: "대형 서점에 가서 예술, 디자인, 음악 코너의 서적들 깊이 있게 훑어보기" },
  { id: "art-180-mid-1", category: "문화예술", duration: 180, difficulty: "중", text: "할머니의 인생 영화 추천받아서 보기" },
  { id: "art-30-low-1", category: "문화예술", duration: 30, difficulty: "하", text: "가장 좋아하는 노래 한 곡을 골라 특정 악기 소리 하나에만 집중해서 들어보기" },
  { id: "art-60-low-1", category: "문화예술", duration: 60, difficulty: "하", text: "예술가들의 작업실 브이로그나 악기 연주 비하인드 영상 보며 영감 얻기" },
  { id: "art-90-low-1", category: "문화예술", duration: 90, difficulty: "하", text: "스마트폰을 비행기 모드로 바꾸고 읽고 싶었던 소설책 집중해서 읽기" },
  { id: "art-120-low-1", category: "문화예술", duration: 120, difficulty: "하", text: "방 불을 모두 끄고 오직 영화 한 편에만 집중할 수 있는 나만의 방구석 영화관 만들기" },
  { id: "art-150-low-1", category: "문화예술", duration: 150, difficulty: "하", text: "잔잔한 백색소음 속에서 한 문장씩 곱씹으며 인문학 서적 읽기" },
  { id: "art-180-low-1", category: "문화예술", duration: 180, difficulty: "하", text: "한 작가의 연작 소설이나 시리즈 도서를 한자리에서 쭉 이어 읽기" },
  { id: "heal-30-up-1", category: "휴식힐링", duration: 30, difficulty: "상", text: "평소 미뤄뒀던 연락처나 사진첩 들어가서 안 쓰는 데이터 싹 정리하기" },
  { id: "heal-60-up-1", category: "휴식힐링", duration: 60, difficulty: "상", text: "우체통 통하여 손편지 보내기" },
  { id: "heal-90-up-1", category: "휴식힐링", duration: 90, difficulty: "상", text: "스마트폰을 완전히 꺼두고 읽고 싶었던 책 집중해서 읽기" },
  { id: "heal-120-up-1", category: "휴식힐링", duration: 120, difficulty: "상", text: "방 안의 가구나 소품 배치를 바꾸며 내 공간 분위기 환기하기" },
  { id: "heal-150-up-1", category: "휴식힐링", duration: 150, difficulty: "상", text: "좋아하는 재료를 듬뿍 넣은 정성스러운 요리 직접 만들어 먹기" },
  { id: "heal-180-up-1", category: "휴식힐링", duration: 180, difficulty: "상", text: "조용한 외곽이나 자연 속 장소를 찾아가 오롯이 나만의 시간 보내기" },
  { id: "heal-30-mid-1", category: "휴식힐링", duration: 30, difficulty: "중", text: "핸드폰, 이어폰 없이 산책하기" },
  { id: "heal-60-mid-1", category: "휴식힐링", duration: 60, difficulty: "중", text: "동네에서 안 가본 골목길로만 크게 한 바퀴 돌고 오기" },
  { id: "heal-90-mid-1", category: "휴식힐링", duration: 90, difficulty: "중", text: "고마운 사람들을 떠올리며 보낼 편지 정성껏 쓰기" },
  { id: "heal-120-mid-1", category: "휴식힐링", duration: 120, difficulty: "중", text: "공원에 가서 취미생활 하기. 운동 책읽기 낮잠 뜨개질 그림 그리기 등." },
  { id: "heal-150-mid-1", category: "휴식힐링", duration: 150, difficulty: "중", text: "푸른 식물들이 가득한 온실 카페 찾아가서 쉬다 오기" },
  { id: "heal-180-mid-1", category: "휴식힐링", duration: 180, difficulty: "중", text: "잔잔한 음악을 틀어놓고 최근의 생각들을 마구 끄적이며 비워내기" },
  { id: "heal-30-low-1", category: "휴식힐링", duration: 30, difficulty: "하", text: "실없는 장난 치기: 숨어있다가 친구 놀래키기 등" },
  { id: "heal-60-low-1", category: "휴식힐링", duration: 60, difficulty: "하", text: "족욕하기" },
  { id: "heal-90-low-1", category: "휴식힐링", duration: 90, difficulty: "하", text: "좋아하는 향의 초를 켜고 방 안의 모든 조명 끄고 누워있기" },
  { id: "heal-120-low-1", category: "휴식힐링", duration: 120, difficulty: "하", text: "침대 이불을 새로 갈고 그 속에서 가장 편한 자세로 낮잠 자기" },
  { id: "heal-150-low-1", category: "휴식힐링", duration: 150, difficulty: "하", text: "만화카페에 가서 따뜻한 음료와 함께 좋아하는 책 쌓아두고 보기" },
  { id: "heal-180-low-1", category: "휴식힐링", duration: 180, difficulty: "하", text: "집에서 가장 편한 옷을 입고 밀린 영화 연달아 정주행하기" },
  { id: "prod-30-up-1", category: "생산성", duration: 30, difficulty: "상", text: "한 달 후의 내 모습을 상상하여 짧은 글 적기" },
  { id: "prod-60-up-1", category: "생산성", duration: 60, difficulty: "상", text: "평소 관심 있었지만 도전해보지 못한 분야의 입문 강의 1시간 수강하기" },
  { id: "prod-90-up-1", category: "생산성", duration: 90, difficulty: "상", text: "지인들을 캐릭터로 한 코미디 영화 시놉시스 기획해보기" },
  { id: "prod-120-up-1", category: "생산성", duration: 120, difficulty: "상", text: "지인에게 나에 대한 피드백을 요청하고, 피드백 내용과 본인에 대한 글 써보기" },
  { id: "prod-150-up-1", category: "생산성", duration: 150, difficulty: "상", text: "인생 버킷리스트 100개 작성하기" },
  { id: "prod-180-up-1", category: "생산성", duration: 180, difficulty: "상", text: "평소 흥미 있었지만 미뤄뒀던 심도 있는 전공/인문 서적 한 권을 완독하고 나만의 결론 출하기" },
  { id: "prod-30-mid-1", category: "생산성", duration: 30, difficulty: "중", text: "365일 뒤의 하루 일정 계획해보기" },
  { id: "prod-60-mid-1", category: "생산성", duration: 60, difficulty: "중", text: "동네 도서관 2층의 2번째 책장에 꽂힌 22번째 책 읽기" },
  { id: "prod-90-mid-1", category: "생산성", duration: 90, difficulty: "중", text: "조용한 카페에, 올해 남은 기간 꼭 지키고 싶은 나만의 루틴 3가지 정립하기" },
  { id: "prod-120-mid-1", category: "생산성", duration: 120, difficulty: "중", text: "메모지를 활용하여 도서관 책에 감상 남기기-책 훼손x" },
  { id: "prod-150-mid-1", category: "생산성", duration: 150, difficulty: "중", text: "나를 주인공으로 한 짧은 단편 소설 도입부 써보기" },
  { id: "prod-180-mid-1", category: "생산성", duration: 180, difficulty: "중", text: "좋아하는 플레이리스트를 크게 튼 채, 방 안의 가구 배치를 바꿔보기" },
  { id: "prod-30-low-1", category: "생산성", duration: 30, difficulty: "하", text: "관심 있는 공부 분야의 책 주문하기" },
  { id: "prod-60-low-1", category: "생산성", duration: 60, difficulty: "하", text: "과거에 적었던 글을 다시 읽고, 퇴고해 보기" },
  { id: "prod-90-low-1", category: "생산성", duration: 90, difficulty: "하", text: "본 미션 이후의 일정 중 한 가지 미루고, 그 시간 동안 아무 목적 없이 동네 골목길 산책하며 풍경 관찰하기" },
  { id: "prod-120-low-1", category: "생산성", duration: 120, difficulty: "하", text: "평소 걷다 발견해 둔 카페에 가서 스마트폰을 끄고 오롯이 나만의 기획과 생각에 잠겨보기" },
  { id: "prod-150-low-1", category: "생산성", duration: 150, difficulty: "하", text: "좋아하는 영화를 소리 없이 틀어두고, 나의 최근 고민들을 마인드맵으로 전부 쏟아내기" },
  { id: "prod-180-low-1", category: "생산성", duration: 180, difficulty: "하", text: "스마트폰 앨범을 보며, 가장 좋았던 순간들을 모아 나만의 인생 하이라이트 앨범 만들기" },
  { id: "soc-30-up-1", category: "사회교제", duration: 30, difficulty: "상", text: "가까운 지인에게 생각지도 못한 깜짝 배달 선물(기프티콘)과 함께 응원 메시지 보내기" },
  { id: "soc-60-up-1", category: "사회교제", duration: 60, difficulty: "상", text: "가까운 지인 3명과 각 지인에게 잘 어울리는 노래를 떠올려보고 노래 추천 연락하기" },
  { id: "soc-90-up-1", category: "사회교제", duration: 90, difficulty: "상", text: "단골 가게(식당, 카페, 상점 등)에 가서 사장님께 가게 칭찬하기" },
  { id: "soc-120-up-1", category: "사회교제", duration: 120, difficulty: "상", text: "지인들과 함께할 수 있는 홈파티나 모임을 기획하고 장소, 메뉴, 타임라인 짜기" },
  { id: "soc-150-up-1", category: "사회교제", duration: 150, difficulty: "상", text: "소중한 사람에게 내 마음을 담은 진심 어린 장문의 편지나 이메일 써서 보내기" },
  { id: "soc-180-up-1", category: "사회교제", duration: 180, difficulty: "상", text: "소중한 사람을 위해 직접 요리를 하여 식사 대접하기" },
  { id: "soc-30-mid-1", category: "사회교제", duration: 30, difficulty: "중", text: "가장 친한 친구에게 전화로 표현하지 않았던 고마운 점 말하기" },
  { id: "soc-60-mid-1", category: "사회교제", duration: 60, difficulty: "중", text: "엄마에게 최근에 빠져있는 취미나 관심사에 대한 대화 나누며 취향 알아가기" },
  { id: "soc-90-mid-1", category: "사회교제", duration: 90, difficulty: "중", text: "오랜만에 연락하는 친구나 동료에게 부담 없는 안부 전화 걸어 도란도란 이야기 나누기" },
  { id: "soc-120-mid-1", category: "사회교제", duration: 120, difficulty: "중", text: "멀리 살거나 자주 못 본 친구와 영상통화를 켜두고 각자 할 일 하거나 랜선 소통하기" },
  { id: "soc-150-mid-1", category: "사회교제", duration: 150, difficulty: "중", text: "친구나 연인과 함께 가보고 싶었던 새로운 동네를 약속 없이 만나 발길 닿는 대로 데이트하기" },
  { id: "soc-180-mid-1", category: "사회교제", duration: 180, difficulty: "중", text: "가족과 영화를 관람하고, 각자의 감상 나누기" },
  { id: "soc-30-low-1", category: "사회교제", duration: 30, difficulty: "하", text: "아빠에게 전화로 사랑한다고 말하기" },
  { id: "soc-60-low-1", category: "사회교제", duration: 60, difficulty: "하", text: "지금 떠오르는 소중한 한 사람을 위한 1만원 이하의 선물 구매하기" },
  { id: "soc-90-low-1", category: "사회교제", duration: 90, difficulty: "하", text: "평소 고마웠던 사람에게 보낼 메시지나 카드를 손글씨로 꾹꾹 눌러쓰며 마음 정리하기" },
  { id: "soc-120-low-1", category: "사회교제", duration: 120, difficulty: "하", text: "카페에서 편안한 지인과 마주 앉아 스마트폰을 치워두고 서로의 최근 고민 깊게 들어주기" },
  { id: "soc-150-low-1", category: "사회교제", duration: 150, difficulty: "하", text: "부모님이나 형제자매와 옛날 앨범이나 사진첩을 함께 넘겨보며 추억 이야기 나누기" },
  { id: "soc-180-low-1", category: "사회교제", duration: 180, difficulty: "하", text: "친한 친구나 지인들을 집으로 초대해 편안한 분위기 속에서 보드게임을 하거나 밤새 수다 떨기" },
  { id: "self-30-up-1", category: "개인유지", duration: 30, difficulty: "상", text: "무채색 사용하지 않고 옷 입기" },
  { id: "self-60-low-1", category: "개인유지", duration: 60, difficulty: "하", text: "하루 중, 스스로가 한 다정한 행동 칭찬하기" },
  { id: "self-90-up-1", category: "개인유지", duration: 90, difficulty: "상", text: "앞으로 1년 동안 이루고 싶은 외적·내적 목표들을 적어 나만의 '성장 가이드북' 작성하기" },
  { id: "self-120-up-1", category: "개인유지", duration: 120, difficulty: "상", text: "내 취향과 가치관이 듬뿍 담긴 나만의 개인 블로그나 SNS 계정 개설하고 첫 글 완성도 있게 쓰기" },
  { id: "self-150-up-1", category: "개인유지", duration: 150, difficulty: "상", text: "나를 위한 완벽한 하루를 기획하고, 온전히 나만의 취향으로 가득 채운 '나 홀로 데이트' 코스 짜기" },
  { id: "self-180-up-1", category: "개인유지", duration: 180, difficulty: "상", text: "내 가치관, 장단점, 미래 계획을 종합하여 나라는 사람을 한 권의 책처럼 정의하는 '자기분석서' 쓰기" },
  { id: "self-30-mid-1", category: "개인유지", duration: 30, difficulty: "중", text: "카카오톡 '나와의 채팅'에서 7일 뒤 나에게 하고 싶은 말 예약메시지로 적기" },
  { id: "self-60-up-1", category: "개인유지", duration: 60, difficulty: "상", text: "앨범에서 2020년도에 촬영한 사진을 보고 가장 즐거웠던 추억 글로 적어보기" },
  { id: "self-90-mid-1", category: "개인유지", duration: 90, difficulty: "중", text: "가보고 싶었던 식당에 가서 저녁 먹기" },
  { id: "self-120-mid-1", category: "개인유지", duration: 120, difficulty: "중", text: "좋아하는 향수 매장이나 편집숍에 가서 내 이미지에 가장 잘 맞는 '인생 향' 찾아오기" },
  { id: "self-150-mid-1", category: "개인유지", duration: 150, difficulty: "중", text: "평소 고치고 싶었던 나쁜 습관을 대체할 수 있는 나만의 루틴 매뉴얼 만들고 포스터로 인쇄하기" },
  { id: "self-180-mid-1", category: "개인유지", duration: 180, difficulty: "중", text: "나만의 아지트가 될 만한 조용하고 아름다운 동네를 찾아가 정처 없이 거닐며 나랑 대화하기" },
  { id: "self-30-low-1", category: "개인유지", duration: 30, difficulty: "하", text: "하루 중, 스스로가 한 다정한 행동 칭찬하기" },
  { id: "self-60-mid-1", category: "개인유지", duration: 60, difficulty: "중", text: "내가 가진 옷들을 활용해 평소에 절대 안 입어본 새로운 스타일로 3가지 착장 코디해보기" },
  { id: "self-90-low-1", category: "개인유지", duration: 90, difficulty: "하", text: "따뜻한 물로 샤워한 뒤 가장 아끼는 향의 로션을 바르고 온전히 나에게만 집중하는 시간 가지기" },
  { id: "self-120-low-1", category: "개인유지", duration: 120, difficulty: "하", text: "평소 해보고 싶었던 명상 유튜브 영상을 틀어놓고 잡생각을 비우며 몸과 마음에 온전히 휴식 주기" },
  { id: "self-150-low-1", category: "개인유지", duration: 150, difficulty: "하", text: "편안한 옷을 입고 방에 누워 내가 가장 좋아하는 아티스트의 음악을 가사집 보며 정주행하기" },
  { id: "self-180-low-1", category: "개인유지", duration: 180, difficulty: "하", text: "좋아하는 간식을 잔뜩 차려두고 인생의 방향성을 잡아준 소중한 책이나 만화책 시리즈 완독하기" },
];

const QUOTES = [
  { type: "시조", text: "물이 흐르면 자연히 도랑이 생긴다", source: "수도거성" },
  { type: "시조", text: "바다는 어떠한 물도 마다하지 않기에 그토록 거대해질 수 있다.", source: "관자, 형세해" },
  { type: "시조", text: "시냇물이 모여 강이 되고, 강물이 모여 바다가 된다", source: "관자, 형세해" },
  { type: "시조", text: "군자는 자기에게서 구하고, 소인은 남에게서 구한다", source: "논어, 위령공" },
  { type: "시조", text: "천하의 어려운 일은 반드시 쉬운 일에서 시작되고, 큰일은 반드시 작은 일에서 시작된다", source: "노자, 덕경" },
  { type: "시조", text: "태산이 높다 하되 하늘 아래 뫼이로다. 오르고 또 오르면 못 오를 리 없건마는", source: "양사언, 태산이 높다 하되" },
  { type: "시조", text: "뿌리 깊은 나무는 바람에 아니 흔들릴새, 꽃이 좋고 열매가 많나니", source: "용비어천가" },
  { type: "시조", text: "물이 깊지 않으면 큰 배를 띄울 힘이 없다", source: "장자" },
  { type: "시조", text: "아름드리 나무도 털끝 같은 싹에서 시작되고, 9층 누대도 한 줌의 흙에서부터 세워지며, 천 리 길도 한 걸음부터 시작된다", source: "노자, 덕경" },
  { type: "시조", text: "매화는 추위의 고통을 겪은 뒤에야 맑은 향기를 뿜는다", source: "명심보감" },
  { type: "시조", text: "국화야 너는 어이 삼월 동풍 다 지내고, 낙목한천에 네 홀로 피었나니", source: "이정보, 국화야 너는 어이" },
  { type: "시조", text: "길이 멀어야 말의 힘을 알고, 날이 오래되어야 사람의 마음을 안다", source: "명심보감" },
  { type: "시조", text: "잘 가노라 닫지 말며 못 가노라 쉬지 마라. 부디 그치지 말고 촌음(寸陰)을 아껴스라. 가다가 중지하면 아니 감만 못하니라", source: "김천택, 잘 가노라 닫지 말며" },
  { type: "시조", text: "꽃이 진다 하고 새들아 슬퍼 마라. 바람에 흩날리니 꽃의 탓 아니로다", source: "송순, 하여가" },
  { type: "속담", text: "티끌 모아 태산이 되리니", source: "" },
  { type: "속담", text: "천 리 길도 한 걸음에서 비롯되리라", source: "" },
  { type: "속담", text: "우물을 파되 한 우물만을 깊이 파라", source: "" },
  { type: "속담", text: "시작이 곧 반이니라", source: "" },
  { type: "속담", text: "낙숫물이 바위를 뚫을지어다", source: "" },
  { type: "속담", text: "고생 끝에 낙이 깃든다", source: "" },
  { type: "속담", text: "꾸준함이 재능을 이기느니라", source: "" },
  { type: "속담", text: "가랑비에 옷 젖듯 서서히 스미느니라", source: "" },
  { type: "속담", text: "한 술 밥으로 어찌 배부르랴", source: "" },
  { type: "속담", text: "노력은 끝내 배신하지 아니하리로다", source: "" },
  { type: "속담", text: "공든 탑이 무너지랴", source: "" },
];
